version: "3.8"
services:
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog
    ports:
      - "3306"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  blog:
    build: .
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8888:8888"
    command: --db_host=postgres
